//
// Generated by class-dump.
//


#include <Foundation/Foundation.h>


@interface SkeletonKing : NSObject
{
    int characterState;
    BOOL onPlatform;
    BOOL onEdge;
    BOOL shotFire;
    BOOL shotImps;
    BOOL filtered;
    int runs;
    int jumpattacks;
    int chargeattacks;
}

- (void)dealloc;
- (void)Imp3;
- (void)Imp2;
- (void)Imp1;
- (void)Impfx3;
- (void)Impfx2;
- (void)Impfx1;
- (void)spawnImps;
- (void)throwboomer;
- (void)shootFireballs;
- (void)novisible;
- (void)bossExplosion;
- (void)chooseAttack;
- (void)switchToIdle;
- (void)stopCharge;
- (void)trail;
- (void)startCharge;
- (void)changeState:(int)arg1;
- (void)charge;
- (void)updateStateWithDeltaTime:(double)arg1;
@end

